version: '3.8'

services:
  backend:
    build:
      context: ./ToDo
      dockerfile: ToDoApi/Dockerfile
    container_name: todo-backend
    ports:
      - "5262:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - todo-network

  frontend:
    build:
      context: ./task-assignment-frontend/task-assignment
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge