version: "3.9"

services:
  todo-api:
    build:
      context: .
      dockerfile: ToDoApi/Dockerfile
    container_name: todo-api
    ports:
      - "5262:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
